estacionamento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Estacionamento"
admin.site.index_title = "Veicular - Estacionamento de Veículos"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('clientepf.urls')),
    path('', include('clientepj.urls')),
    path('', include('funcionario.urls')),
    path('', include('vaga.urls')),
    path('', include('veiculo.urls')),
    path('', include('movimentacao.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

movimentacao/urls.py
from django.urls import path
from .views import MovimentacoesView, MovimentacaoAddView, MovimentacaoUpDateView, MovimentacaoDeleteView

urlpatterns = [
    path('movimentacoes', MovimentacoesView.as_view(), name='movimentacoes'),
    path('movimentacao/adicionar/', MovimentacaoAddView.as_view(), name='movimentacao_adicionar'),
    path('<int:pk>/movimentacao/editar/', MovimentacaoUpDateView.as_view(), name='movimentacao_editar'),
    path('<int:pk>/movimentacao/apagar/', MovimentacaoDeleteView.as_view(), name='movimentacao_apagar'),
]

movimentacao/models.py
from django.db import models




class Movimentacao(models.Model):
    SITUACAO_OPCOES = (
        ('O', 'Ocupado'),
        ('L', 'Livre'),
        ('T', '------')
    )

    entrada = models.DateField(auto_now_add=True)
    saida = models.DateField('Saída', help_text='Hora de saida')
    valor_pago = models.DecimalField('Valor', decimal_places=2, max_digits=6, help_text='Valor da estada')
    tempo = models.DecimalField('Tempo', decimal_places=2, max_digits=6, help_text='Tempo de permanência')
    vaga = models.ForeignKey('vaga.Vaga', verbose_name='Vaga', help_text='Vaga',
                             on_delete=models.CASCADE)
    funcionario = models.ForeignKey('funcionario.Funcionario', verbose_name='Funcionario', help_text='Nome do funcionario',
                                    on_delete=models.CASCADE)
    situacao = models.CharField('Situacão', max_length=15, help_text="Situacão da vaga", choices=SITUACAO_OPCOES,
                                default='T')
    class Meta:
        verbose_name = 'Movimentacao'
        verbose_name_plural = 'Movimentacoes'
        ordering = ['entrada', ]

    def __str__(self):
        return f'Vaga: {self.vaga} - Funcionário: {self.funcionario}'

movimentacao/forms.py
from django import forms

from movimentacao.models import Movimentacao
from vaga.models import Vaga
from funcionario.models import Funcionario
class MovimentacaoListForm(forms.Form):
    SITUACAO_OPCOES = (
        ('O', 'Ocupado'),
        ('L', 'Livre'),
        ('T', '----------')
    )

    funcionario = forms.ModelMultipleChoiceField(label='Funcionário:', widget=forms.Select(
    attrs={'class': 'select is-fullwidth'}), queryset=Funcionario.objects.all(), required=False)

    vaga = forms.ModelMultipleChoiceField(label='Vaga:', widget=forms.Select(
    attrs={'class': 'select is-fullwidth'}), queryset=Vaga.objects.all(), required=False)

    situacao = forms.ChoiceField(label='Situação:', widget=forms.Select(
    attrs={'class': 'select is-fullwidth'}), choices=SITUACAO_OPCOES, required=False)



class MovimentacaoModelForm(forms.ModelForm):
    class Meta:
        model = Movimentacao
        fields = ['saida', 'valor_pago', 'tempo', 'vaga', 'funcionario', 'situacao']
        widgets = {
            'saida': forms.TimeInput(format='%H:%M'),
            'valor_pago': forms.NumberInput(attrs={'class': 'input', 'placeholder': 'Digite o valor pago'}),
            'tempo': forms.NumberInput(attrs={'class': 'input', 'placeholder': 'Digite o tempo de permanência'}),
            'vaga': forms.Select(attrs={'class': 'input', 'placeholder': 'Selecione a vaga utilizada'}),
            'funcionario': forms.Select(attrs={'class': 'input', 'placeholder': 'Selecione o funcionário responsável'}),
            'situacao': forms.Select(attrs={'class': 'input', 'placeholder': 'Selecione a situação'}),
        }

movimentacao/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib import messages
import movimentacao
from home.utils import HtmlToPdf
from movimentacao.forms import MovimentacaoModelForm
from vaga.models import Vaga
from .forms import MovimentacaoListForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Movimentacao
from django.core.paginator import Paginator


class MovimentacoesView(ListView):
    model = Movimentacao
    template_name = 'movimentacoes.html'

    def get_context_data(self, **kwargs):
        context = super(MovimentacoesView, self).get_context_data(**kwargs)
        if self.request.GET:
            form = MovimentacaoListForm(self.request.GET)
        else:
            form = MovimentacaoListForm()

        context['form'] = form

        return context

    def get_queryset(self, *args, **kwargs):
        qs = super(MovimentacoesView, self).get_queryset()

        if self.request.GET:
            form = MovimentacaoListForm(self.request.GET)
            if form.is_valid():
                funcionario = form.cleaned_data.get('funcionario')
                vaga = form.cleaned_data.get('vaga')
                situacao = form.cleaned_data.get('situacao')

                if funcionario:
                    qs = qs.filter(funcionario=funcionario)
                if vaga:
                    qs = qs.filter(vaga=vaga)
                if situacao != 'T':
                    qs = qs.filter(situacao_icontains=situacao)

        return qs

        if qs.count() > 0:
            paginator = Paginator(qs, 10)
            listagem = paginator.get_page(self.request.GET.get('page'))
            return listagem
        else:
            return messages.info(self.request, "Não existem movimentações cadastradas!")

    def get(self, *args, **kwargs):
        if self.request.GET.get('imprimir') == 'pdf':
            html_pdf = HtmlToPdf(arquivo='movimentacoes_pdf', qs=self.get_queryset())
            return html_pdf.response
        else:
            return super(MovimentacoesView, self).get(*args, **kwargs)

class MovimentacaoAddView(SuccessMessageMixin, CreateView):
    form_class = MovimentacaoModelForm
    model = Movimentacao
    template_name = 'movimentacao_form.html'
    success_url = reverse_lazy('movimentacoes')
    sucess_message = "Estacionado com sucesso!"
    def post(self, request, *args, **kwargs):
        form = MovimentacaoListForm(self.request.POST)
        if form.is_valid():
            funcionario = form.cleaned_data.get('funcionario')
            vaga = form.cleaned_data.get('vaga')
            situacao = form.cleaned_data('situacao')
            if situacao == 'O':
                for vaga in movimentacao:
                    v = Vaga.objects.get(id=vaga.vaga.id)
                    if v.quantidade < vaga.quantidade:
                        messages.info(self.request, 'Estacionamento cheio!'
                                                        ' Impossível estacionar outro veículo')
        return super(MovimentacaoAddView, self).post(request, *args, **kwargs)

class MovimentacaoUpDateView(SuccessMessageMixin, UpdateView):
    form_class = MovimentacaoModelForm
    model = Movimentacao
    template_name = 'movimentacao_form.html'
    success_url = reverse_lazy('movimentacoes')
    sucess_message = "Movimentaçao atualizada com sucesso!"

class MovimentacaoDeleteView(SuccessMessageMixin, DeleteView):
    model = Movimentacao
    template_name = 'movimentacao_apagar.html'
    success_url = reverse_lazy('movimentacoes')
    sucess_message = "Movimentação excluída com sucesso!"

movimentacao/templates/movimentacao_apagar.html
{% extends 'base.html' %}
{% block content %}
<section class="section">
    <div class="container">
        <div class="columns is-mobile">
            <div class="column is-half is-offset-one-quarter">
                <h3 class="title is-size-3">Dados da Movimentação</h3>
                <p class="p-2 mt-2"><strong>Entrada: </strong> {{ object.entrada}} </p>
                <p class="p-2 mt-2"><strong>Preço: </strong> {{ object.saida }} </p>
                <p class="p-2 mt-2"><strong>Valor Pago: </strong> {{ object.valor_pago}} </p>
                <p class="p-2 mt-2"><strong>Vaga: </strong> {{ object.vaga}} </p>
                <p class="p-2 mt-2"><strong>Funcionario: </strong> {{ object.funcionario}} </p>
                <p class="p-2 mt-2"><strong>Situação: </strong> {{ object.situacao}} </p>

                {% csrf_token %}
                <p> Confirma a exclusão da movimentação"{{ object }}"? </p>
                <br/>
                <button class="button is-link is-primary" type="submit">Apagar</button>
                <button class="button is-danger is-pulled-right" type="reset">
                    <a href="{% url 'movimentacoes' %}">Cancelar</a>
                </button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

movimentacao/templates/movimentacao_form.html
{% extends "base.html" %}
{% block content %}
    <section class="section">
        <div class="container">
            <div class="column is-mobile">
                <div class="column is-half is-off-set-one-quarter">
                    <h3 class="title is-size-3">Cadastro de Movimentações</h3>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="field">
                                    {% if field.value is not empty %}
                                        <label class="label is-capitalized">{{ field.label }}: {{ field }} </label>
                                {% else %}
                                        <label class="label is-capitalized">{{ field.label }}: {{ field }} </label>
                                {% endif %}
                                {% if field.help_text %}
                                    <p class="help">{{ field.help_text }}</p>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p class="help is-danger"> {{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <button class="button is-link is-primary" type="submit">Salvar</button>
                        <button class="button is-danger is-pulled-right" type="reset">
                            <a href="{% url 'movimentacoes' %}">Cancelar</a>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

movimentacao/templates/movimentacoes.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="section has-background-link-light">
    <div class="container">
        <form id="form ListaMovimentacoes" action="" method="GET">
            <input type="hidden" name="imprimir" id="imprimir" value="">
            <div class="field is-grouped is-flex is-align-items center is-flex-wrap-wrap">
                <label class="label p-2 mt-2">{{ form.funcionario.label }}</label>
                <div class="control is-expanded">
                    {{ form.funcionario }}
                </div>
                <label class="label p-2 mt-2">{{ form.vaga.label }}</label>
                <div class="control is-expanded">
                    {{ form.vaga }}
                </div>
                <label class="label p-2 mt-2">{{ form.situacao.label }}</label>
                <div class="control is-expanded">
                    {{ form.situacao }}
                </div>
                <div class="control">
                    <button type="button" class="button is-link" onclick="geraPdf('', 'formListaMovimentacoes');">
                        Buscar
                    </button>
                </div>
                <div class="control">
                    <button type="button" class="button is-link" onclick="geraPdf('pdf', 'formListaMovimentacoes');">
                        Imprimir
                    </button>
                </div>
            </div>
        </form>
        {% if object_list %}
        <div style="text-align: center;"><h1 class="subtitle is-size-4">Movimentações</h1></div>
        <div class="table">
            <table class="table is-table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                <thead>
                <tr>
                    <th class="has-text-centered">Entrada</th>
                    <th class="has-text-centered">Saida</th>
                    <th class="has-text-centered">Valor Pago</th>
                    <th class="has-text-centered">Tempo</th>
                    <th class="has-text-centered">Vaga</th>
                    <th class="has-text-centered">Funcionário</th>
                    <th class="has-text-centered">Situacão</th>
                </tr>
                </thead>
                <tbody>
                {% for movimentacao in object_list %}
                <tr>
                    <td> {{ movimentacao.entrada }}</td>
                    <td> {{ movimentacao.saida }}</td>
                    <td> {{ movimentacao.valor_pago }}</td>
                    <td> {{ movimentacao.tempo }}</td>
                    <td> {{ movimentacao.vaga }}</td>
                    <td> {{ movimentacao.funcionario }}</td>
                    <td> {{ movimentacao.get_situacao_display }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% include "paginator.html" %}
</section>
{% endif %}
{% endblock %}

movimentacao/templates/movimentacoes_pdf.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

{% block head %}
    {% include "head.html" %}
{% endblock %}

<body>
    <section class="section">
        <div class="container">
            <h1 class="title has-text-centered has-text-weight-bold">Cadastro de Movimentacoes</h1>
        </div>
    </section>
    <section class="section has-background-link-light">
        {% if object_list %}
        <div style="text-align: center;"><h1 class="subtitle is-size-4">Movimentacoes</h1></div>
        <div class="table">
            <table class="table is-table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                <thead>
                    <tr>
                        <th class="has-text-centered">Entrada</th>
                        <th class="has-text-centered">Saida</th>
                        <th class="has-text-centered">Valor Pago</th>
                        <th class="has-text-centered">Funcionario</th>
                        <th class="has-text-centered">Situação</th>
                    </tr>
                </thead>
                <tbody>
                    {% for movimentacao in object_list%}
                    <tr>
                        <td> {{movimentacao.entrada}} </td>
                        <td> {{movimentacao.saida}} </td>
                        <td> {{movimentacao.valorpago}} </td>
                        <td> {{movimentacao.funcionario}} </td>
                        <td> {{movimentacao.get_situacao_display}} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
            <h2>Nao existem movimentaçoes cadastrados</h2>
        {% endif %}
    </section>
</body>
</html>

movimentacao/templates/movimentaçoes_pdf.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

{% block head %}
    {% include "head.html" %}
{% endblock %}

<body>
    <section class="section">
        <div class="container">
            <h1 class="title has-text-centered has-text-weight-bold">Cadastro de Movimentacoes</h1>
        </div>
    </section>
    <section class="section has-background-link-light">
        {% if object_list %}
        <div style="text-align: center;"><h1 class="subtitle is-size-4">Movimentacoes</h1></div>
        <div class="table">
            <table class="table is-table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                <thead>
                    <tr>
                        <th class="has-text-centered">Entrada</th>
                        <th class="has-text-centered">Saida</th>
                        <th class="has-text-centered">Valor Pago</th>
                        <th class="has-text-centered">Veiculo</th>
                        <th class="has-text-centered">Funcionario</th>
                        <th class="has-text-centered">Situação</th>
                    </tr>
                </thead>
                <tbody>
                    {% for movimentacao in object_list%}
                    <tr>
                        <td> {{movimentacao.entrada}} </td>
                        <td> {{movimentacao.saida}} </td>
                        <td> {{movimentacao.valorpago}} </td>
                        <td> {{movimentacao.veiculo}} </td>
                        <td> {{movimentacao.funcionario}} </td>
                        <td> {{movimentacao.get_situacao_display}} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
            <h2>Nao existem movimentaçoes cadastrados</h2>
        {% endif %}
    </section>
</body>
</html>